return {
	START_INTERMISSION = "START_INTERMISSION",
	INTERMISSION = "INTERMISSION",
	WAVE_IN_PROGRESS = "WAVE_IN_PROGRESS",
	GAME_OVER = "GAME_OVER",
	GAME_OVER_WIN = "GAME_OVER_WIN",
	WAITING = "WAITING"
}
